version: '2'
services:
  tcpdump:
    build: ./
    environment:
      - ES_HOST=${ES_HOST}
      - LOGSTASH_USER=${LOGSTASH_USER}  
      - PASSWORD=${PASSWORD}  
    volumes:
      - ${PATH_CONF}/:/usr/share/logstash/pipeline/
      - ${PATH_LOGS}/:/logs/
    ports:
      - 5046:5046
    networks:
      - esnet
networks:
  esnet:
